spring:
  profiles:
    active: development

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/helpdesk?autoReconnect=true
    username: root
    password: root
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

  jackson:
    serialization:
      indent_output: true

  data:
    rest:
      basePath: /api

  devtools:
    livereload:
      enabled: true

  redis:
    host: 127.0.0.1
    port: 6379

  thymeleaf:
    cache: true

server:
  tomcat:
    access_log_enabled: true
basedir: target/tomcat
